ESC                 quit
WHEEL_UP            seek  5
WHEEL_DOWN          seek  -5
UP                  add sub-pos -1
DOWN                add sub-pos 1
/                   cycle audio
HOME                seek 0 absolute
MOUSE_BTN2          cycle fullscreen
MOUSE_BTN0          cycle pause
MOUSE_BTN0_DBL      ignore
KP_SUBTRACT         repeatable script-message-to volunit  dB add -0.5
KP_ADD              repeatable script-message-to volunit  dB add +0.5
,                   seek -0.05 exact
.                   seek 0.05 exact
+					repeatable script-message-to volunit  dB add +0.5
-					repeatable script-message-to volunit  dB add -0.5
d                   cycle-values video-sync display-resample audio
u                   cycle-values sub-ass-override yes force no
a                   cycle secondary-sid
r                   add sub-scale 0.01
t                   add sub-scale -0.01
p                   cycle osd-level
h                   cycle-values hwdec auto-safe no
F1                  cycle-values tscale-blur 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1 2 3 4 5
F2                  cycle-values osd-msg1="FPS: ${estimated-display-fps}"
F3                  cycle-values scale oversample ewa_lanczos4sharpest gaussian bilinear
F4                  cycle-values tone-mapping auto st2094-40
F5                  cycle-values dscale oversample ewa_lanczos4sharpest gaussian bilinear
F6                  cycle-values video-sync display-resample display-vdrop display-tempo display-adrop
F7                  change-list glsl-shaders toggle "~~/shaders/Anime4K_Restore_CNN_UL.glsl"
F8                  cycle-values audio-channels auto stereo mono
F9 					cycle-values tscale-antiring 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1 0
F10					cycle-values tscale-taper 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1 0
F11                 cycle-values tscale-radius 0.5 0.6 0.7 0.8 0.9 1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9 2.0 2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3.0
